### ISSUE TITLE
The accuracy of reproduction is low.

### ISSUE THREAD

**Issue by HMCCMH** [fulliu/lc#1]
I don't why the accuracy of the reproduction is low. I didn't change any parameters.

Here is the result:
```
[W Context.cpp:203] Warning: torch.backends.cuda.preferred_linalg_library is an experimental feature. If you see any error or unexpected behavior when this flag is set please file an issue on GitHub. (function operator())
20240113_115220|dataset@195: loading annotations from image list ...
20240113_115220|ptnet@24: Model:: total_bit_cnt: 0
20240113_115221|model.cdpn_resnet@205: loaded resnet backbone from pytorch model zoo
20240113_115224|lib.utils.checkpoint@275: loaded model from output/glmo-1/model_best_20_0.1120.pth
100%|##########| 37/37 [00:23<00:00,  1.58it/s]
100%|##########| 1170/1170 [00:02<00:00, 546.69it/s]
20240113_115250|__main__@262:
weighted
object  AUCadi_10_p11  AUCad_10_p11  AUCadi_10_all  AUCad_10_all  add(-s)_0.10  add-s_0.10  add_0.10
ape     73.90          58.85         69.72          54.95         11.20         36.58       11.20
Avg(1)  73.90          58.85         69.72          54.95         11.20         36.58       11.20


[W Context.cpp:203] Warning: torch.backends.cuda.preferred_linalg_library is an experimental feature. If you see any error or unexpected behavior when this flag is set please file an issue on GitHub. (function operator())
20240113_113817|dataset@195: loading annotations from image list ...
20240113_113818|ptnet@24: Model:: total_bit_cnt: 0
20240113_113818|model.cdpn_resnet@205: loaded resnet backbone from pytorch model zoo
20240113_113821|lib.utils.checkpoint@275: loaded model from output/glmo-1/model_final.pth
100%|##########| 37/37 [00:24<00:00,  1.49it/s]
100%|##########| 1170/1170 [00:03<00:00, 373.65it/s]
20240113_113850|__main__@262:
weighted
object  AUCadi_10_p11  AUCad_10_p11  AUCadi_10_all  AUCad_10_all  add(-s)_0.10  add-s_0.10  add_0.10
ape     22.97          11.36         21.27          10.11         0.00          3.50        0.00
Avg(1)  22.97          11.36         21.27          10.11         0.00          3.50        0.00

```

The python version is 3.8.
The CUDA environment is 10.2.

I'd appreciate it if you could give me a possible reason.

Thank you!

**Comment by fulliu** [comment]
Then you may check your training and testing data.

**Comment by HMCCMH** [comment]
I have checked the training and testing data. They are right. I also tried it on CUDA 11.6 (3090) and the performance is close to that mentioned in the paper. The CUDA version may affect the training of the model.

**Comment by HMCCMH** [comment]
And I found that the best performance is not the epoch 80. Did you choose the best performance during the whole epoch or use the performance of epoch 80?

**Comment by fulliu** [comment]
> I have checked the training and testing data. They are right. I also tried it on CUDA 11.6 (3090) and the performance is close to that mentioned in the paper. The CUDA version may affect the training of the model.

That's interesting because I just tried both cuda 11.3 and 10.2 on a 2080ti machine before my reply. 
Glad to find it finally works.

**Comment by fulliu** [comment]
> And I found that the best performance is not the epoch 80. Did you choose the best performance during the whole epoch or use the performance of epoch 80?

The best model generally does not coincide with the final model, we follow our baseline to decide which model's result to report. It the final model for the glmo config.

**Comment by HMCCMH** [comment]
Thanks for your quick reply!
