### ISSUE TITLE
zebra-LC 推理速度问题

### ISSUE THREAD

**Issue by dazaier** [fulliu/lc#2]
你好，请问你有对比过原始zebra 和 zebra-LC的推理时间吗？尤其是pnp的时间，因为我看原始zebra用progressive-X求解PNP，导致推理一张图片的结果比较久，请问如果用zebra-LC会快很多吗？多谢！

**Comment by fulliu** [comment]
会快一些，就是opencv solvepnpransac的用时+一个ceres solver的优化

**Comment by dazaier** [comment]
好的，多谢，我自己替换成opencv的solvepnpransac 也是会快，我以为你这个会更快。我看你在table 3 对比过 epro-pnp 的pnp layers time, 你的时间比epro-pnp要快不少，是不是说明zebra+epro-pnp 推理时间也很慢呀。我现在的显卡比较垃圾，所以想优化一下zebra 的pnp时间。

**Comment by fulliu** [comment]
表里是训练用的时间，包含了梯度计算之类的。只推理的话我没比较过，估计很难快过solvepnpransac

**Comment by dazaier** [comment]
好的，多谢多谢
