### ISSUE TITLE
The issue in training stage

### ISSUE THREAD

**Issue by helloyuning** [fulliu/lc#4]
Thanks for your greate works and sharing!

I have trained the model by myslf and i found the error(figure) when epoch start from 37.
Also I saved all the model weights,
but it seems the best weight is from epoch 20.(I'm not sure it's normal or not)

![er](https://github.com/user-attachments/assets/bc41b495-a2e2-478d-a277-da399ed66cd5)

thanks,
yuning

**Comment by fulliu** [comment]
The error may be related to some software/hardware environment change. 
The best weight should be normal
